INSERT INTO Publisher(name, email, phone) VALUES('Graywolf Press', 'Graywolf.Press@gmail.com', '323-345-3234')
INSERT INTO Publisher(name, email, phone) VALUES('Penguin Books', 'Penguin.Books@gmail.com', '606-586-4859')
INSERT INTO Publisher(name, email, phone) VALUES('Dzanc Books', 'Dzanc.Books@gmail.com', '909-485-1023')
INSERT INTO Publisher(name, email, phone) VALUES('Akashic Books', 'Akashic.Books@gmail.com', '493-483-2939')
INSERT INTO Publisher(name, email, phone) VALUES('Random House', 'Random.House@gmail.com', '760-483-2934')